spring.application.name=edutrade
# ===============================
# = DATA SOURCE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/edutrade
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# T? t?o/t? update b?ng
spring.jpa.hibernate.ddl-auto=update
# Hi?n th? câu SQL trong console
spring.jpa.show-sql=true
# Format SQL cho d? ??c
spring.jpa.properties.hibernate.format_sql=true
# Dialect MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
